# Generated by Django 5.1.4 on 2025-01-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_product_pack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pack_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
