# Generated by Django 5.1.4 on 2025-02-05 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_package_pack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='damage_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='delivered_by',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='leader_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maint_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='recieved_by',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Good', 'Good'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
