# Generated by Django 5.1.4 on 2025-02-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_maintenance_damage_date_maintenance_delivered_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='recieved_by',
            new_name='received_by',
        ),
    ]
