# Generated by Django 5.1.4 on 2025-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_rename_recieved_by_maintenance_received_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Good', 'Good'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
