# Generated by Django 5.1.4 on 2025-02-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_remove_inventory_image_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='real_quantity',
            new_name='remain_quantity',
        ),
    ]
