# Generated by Django 5.1.4 on 2025-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('WH', 'WH'), ('user', 'user')], default='user', max_length=50),
        ),
    ]
