# Generated by Django 5.1.4 on 2025-02-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
